# Generated by Django 4.2.6 on 2024-02-13 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('trackCode', models.CharField(editable=False, max_length=10, unique=True)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('nick_name', models.CharField(blank=True, max_length=50)),
                ('county', models.CharField(default='', max_length=50)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('eye_color', models.CharField(default='', max_length=20)),
                ('hair_color', models.CharField(default='', max_length=20)),
                ('age', models.PositiveIntegerField(default=20)),
                ('location', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/missing_persons')),
                ('gender', models.CharField(default='', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoundPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('county', models.CharField(default='', max_length=50)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('eye_color', models.CharField(default='', max_length=20)),
                ('hair_color', models.CharField(default='', max_length=20)),
                ('age', models.PositiveIntegerField(default=20)),
                ('location', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/seen_persons')),
                ('gender', models.CharField(default='', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
