# Generated by Django 4.2.6 on 2024-03-26 20:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foundperson',
            name='county',
        ),
        migrations.RemoveField(
            model_name='foundperson',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='foundperson',
            name='location',
        ),
        migrations.RemoveField(
            model_name='foundperson',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='county',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='location',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='MissingPersonLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('time_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('missing_person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Api.missingperson')),
            ],
        ),
        migrations.CreateModel(
            name='FoundPersonLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('time_found', models.DateTimeField(default=django.utils.timezone.now)),
                ('found_person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Api.missingperson')),
            ],
        ),
    ]
