# Generated by Django 4.2.6 on 2023-10-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_alter_missingperson_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='trackCode',
            field=models.CharField(default='', editable=False, max_length=10, unique=True),
        ),
    ]
