# Generated by Django 4.2.6 on 2023-10-31 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_missingperson_trackcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='trackCode',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
