# Generated by Django 4.2.4 on 2023-09-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('code', models.IntegerField()),
                ('matched', models.BooleanField(default=False)),
                ('age', models.IntegerField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
