# Generated by Django 4.2.4 on 2023-09-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Find_Me_App', '0002_alter_person_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='location',
            field=models.CharField(default='Nairobi', max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='code',
            field=models.IntegerField(default='LSTZWVGISPIIG234'),
        ),
    ]
