# Generated by Django 4.2.4 on 2023-09-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Find_Me_App', '0003_person_location_alter_person_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='code',
            field=models.CharField(default='LSTXTGBIBDFZB234', max_length=10),
        ),
    ]
