# Generated by Django 4.2.4 on 2023-09-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Find_Me_App', '0006_foundperson_alter_person_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='code',
            field=models.CharField(default='LSTFVAEDGXONJ254', max_length=20),
        ),
    ]
