# Generated by Django 4.2.4 on 2023-09-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Find_Me_App', '0008_missingperson_rename_foundperson_reportedseenperson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='code',
            field=models.CharField(default='LSTOKQEFSYZBB254', max_length=20),
        ),
    ]
