# Generated by Django 4.2.4 on 2023-09-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Find_Me_App', '0009_alter_missingperson_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='code',
            field=models.CharField(default='LSTATKEPYIIHN254', max_length=20),
        ),
    ]
