# Generated by Django 4.2.4 on 2023-09-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Find_Me_App', '0010_alter_missingperson_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingperson',
            name='code',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='description',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='matched',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='reported_at',
        ),
        migrations.RemoveField(
            model_name='reportedseenperson',
            name='description',
        ),
        migrations.RemoveField(
            model_name='reportedseenperson',
            name='location',
        ),
        migrations.RemoveField(
            model_name='reportedseenperson',
            name='matched',
        ),
        migrations.RemoveField(
            model_name='reportedseenperson',
            name='reported_at',
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='age',
            field=models.IntegerField(default=23),
        ),
        migrations.AlterField(
            model_name='reportedseenperson',
            name='age',
            field=models.IntegerField(default=10),
        ),
    ]
