# Generated by Django 4.2.4 on 2023-09-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Find_Me_App', '0012_alter_reportedseenperson_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedseenperson',
            name='description',
            field=models.CharField(default='Tall', max_length=1000),
        ),
        migrations.AlterField(
            model_name='reportedseenperson',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
