# Generated by Django 4.2.4 on 2023-09-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Find_Me_App', '0013_reportedseenperson_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='description',
            field=models.CharField(default='Tall', max_length=1000),
        ),
    ]
