# Generated by Django 4.2.4 on 2023-09-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Find_Me_App', '0015_reportedseenperson_matched'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='image',
            field=models.ImageField(default='', upload_to='Find_Me_App/Missing_persons-images'),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='trackCode',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='reportedseenperson',
            name='image',
            field=models.ImageField(default=' ', upload_to='Find_Me_App/Reported_seen_persons-images'),
        ),
    ]
