# Generated by Django 4.2.4 on 2023-09-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Find_Me_App', '0017_alter_missingperson_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='image',
            field=models.ImageField(default='', upload_to='Mp_Imgs'),
        ),
    ]
