# Generated by Django 4.2.4 on 2023-09-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Find_Me_App', '0020_alter_reportedseenperson_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='image',
            field=models.ImageField(default='', upload_to='Find_Me_App/Mp_Imgs'),
        ),
        migrations.AlterField(
            model_name='reportedseenperson',
            name='image',
            field=models.ImageField(default=' ', upload_to='Find_Me_App/Fp_Imgs'),
        ),
    ]
