# Generated by Django 4.2.4 on 2023-09-16 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Find_Me_App', '0021_alter_missingperson_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportedseenperson',
            name='image',
        ),
    ]
