# Generated by Django 4.2.4 on 2023-09-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Find_Me_App', '0022_remove_reportedseenperson_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedseenperson',
            name='image',
            field=models.ImageField(default=' ', upload_to='Find_Me_App/Fp_Imgs'),
        ),
    ]
