# Generated by Django 4.2.4 on 2023-09-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Find_Me_App', '0023_reportedseenperson_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='trackCode',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
